[package]
name = "tor_to_arti"
version = "0.1.0"
edition = "2024"
authors = ["hardcase"]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
anyhow = "1.0.100"
chrono = "0.4.43"
serde = { version = "1.0.136", features = ["derive"] }
toml_edit = "0.24.0"
tempfile = "3.24.0"
