[package]
name = "tor_to_arti"
version = "0.1.0"
edition = "2024"
authors = ["hardcase"]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
anyhow = "1.0.100"
chrono = "0.4.43"
toml = "0.9.11"
serde = { version = "1.0.136", features = ["derive"] }
